CREATE USER admin WITH PASSWORD 'admin';

CREATE DATABASE IF NOT EXISTS notification_db;
GRANT ALL PRIVILEGES ON DATABASE notification_db TO admin;

CREATE DATABASE IF NOT EXISTS defense_db;
GRANT ALL PRIVILEGES ON DATABASE defense_db TO admin;

CREATE DATABASE IF NOT EXISTS resource_db;
GRANT ALL PRIVILEGES ON DATABASE resource_db TO admin;

CREATE DATABASE IF NOT EXISTS user_service_db;
GRANT ALL PRIVILEGES ON DATABASE user_service_db TO admin;

CREATE DATABASE IF NOT EXISTS projects_db;
GRANT ALL PRIVILEGES ON DATABASE projects_db TO admin;

CREATE DATABASE IF NOT EXISTS scheduling_db;
GRANT ALL PRIVILEGES ON DATABASE scheduling_db TO admin;

